x = float(input("Enter the first number:- "))
y = float(input("Enter the second number:-"))
add = x + y
sub = x - y
mul = x * y
div = x / y
floor_division = int(x // y)
modulus = x % y
x = 2
y = 5
Exponential = x ** y
print("Addition =",add)
print("Subtract  =",sub)
print("Mulitfly =",mul)
print("Divide =",div)
print("Floor divide =",floor_division)
print("Remainder =",modulus)
print("Exponential =",Exponential)